# Generated by Django 3.2.5 on 2022-06-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('persona_contacto', models.CharField(max_length=100)),
                ('numero_identificacion_fiscal', models.CharField(max_length=15)),
            ],
        ),
    ]
